name: employee_work
description: "Family Project help my family with they work manage employee."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  fl_chart: ^0.69.2
  equatable: ^2.0.7
  audioplayers: ^6.4.0
  bloc: ^9.0.0
  flash: ^3.1.1
  go_router: ^15.1.1
  uuid: ^4.5.1
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^3.1.2
  flutter_svg: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_tts: ^4.2.2
  image_picker: ^1.1.2
  device_info_plus: ^11.3.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/sounds/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: KantumruyPro
      fonts:
        - asset: assets/fonts/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KantumruyPro-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
